
from PyQt5 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_headSettingsMainWindow(object):
    def setupUi(self, headSettingsMainWindow):
        if headSettingsMainWindow.objectName():
                 headSettingsMainWindow.setObjectName("SettingsMainWindow")
        headSettingsMainWindow.resize(1366, 768)
        headSettingsMainWindow.showMaximized()
        headSettingsMainWindow.setStyleSheet("QMainWindow{\n"
"background-image: url(images/new.png);\n"
"}")
        self.centralwidget = QWidget(headSettingsMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topbar = QFrame(self.centralwidget)
        self.topbar.setMinimumSize(QSize(0, 0))
        self.topbar.setStyleSheet("QFrame{}\n"
"background-color: rgb(225, 225, 225);")
        self.topbar.setFrameShape(QFrame.NoFrame)
        self.topbar.setFrameShadow(QFrame.Raised)
        self.topbar.setObjectName("topbar")
        self.horizontalLayout = QHBoxLayout(self.topbar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QFrame(self.topbar)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QFrame.NoFrame)
        self.frame_3.setFrameShadow(QFrame.Plain)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.settings = QPushButton(self.frame_3)
        self.settings.setText("")
        icon = QIcon()
        icon.addPixmap(QPixmap("images/00599149e2ec717872085650fc8c1f05-seo-settings-colored-stroke-icon-by-vexels.png"), QIcon.Normal, QIcon.Off)
        self.settings.setIcon(icon)
        self.settings.setIconSize(QSize(100, 100))
        self.settings.setFlat(True)
        self.settings.setObjectName("settings")
        self.verticalLayout_4.addWidget(self.settings)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QFrame(self.topbar)
        self.frame_4.setStyleSheet("background-color: rgb(225, 37, 52)")
        self.frame_4.setFrameShape(QFrame.NoFrame)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout.addWidget(self.frame_4)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 6)
        self.content = QFrame(self.centralwidget)
        self.content.setFrameShape(QFrame.NoFrame)
        self.content.setFrameShadow(QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout_2 = QHBoxLayout(self.content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_5 = QFrame(self.content)
        self.frame_5.setFrameShape(QFrame.NoFrame)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.left = QFrame(self.frame_5)
        self.left.setMinimumSize(QSize(70, 0))
        self.left.setStyleSheet("\n"
"background-color: rgb(225, 37, 52)")
        self.left.setFrameShape(QFrame.NoFrame)
        self.left.setFrameShadow(QFrame.Raised)
        self.left.setObjectName("left")
        self.verticalLayout_2 = QVBoxLayout(self.left)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_6 = QFrame(self.left)
        self.frame_6.setFrameShape(QFrame.NoFrame)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.changepassword = QPushButton(self.frame_6)
        self.changepassword.setText("")
        icon3 = QIcon()
        icon3.addPixmap(QPixmap("images/250130-200.png"), QIcon.Normal, QIcon.Off)
        self.changepassword.setIcon(icon3)
        self.changepassword.setIconSize(QSize(100, 100))
        self.changepassword.setFlat(True)
        self.changepassword.setObjectName("changepassword")
        self.verticalLayout_5.addWidget(self.changepassword)
        self.label_6 = QLabel(self.frame_6)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.logout = QPushButton(self.frame_6)
        self.logout.setStyleSheet("")
        self.logout.setText("")
        icon4 = QIcon()
        icon4.addPixmap(QPixmap("images/prime_log_out-512.png"), QIcon.Normal, QIcon.Off)
        self.logout.setIcon(icon4)
        self.logout.setIconSize(QSize(90, 90))
        self.logout.setFlat(True)
        self.logout.setObjectName("logout")
        self.verticalLayout_5.addWidget(self.logout)
        self.label_5 = QLabel(self.frame_6)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.back = QPushButton(self.frame_6)
        self.back.setText("")
        icon5 = QIcon()
        icon5.addPixmap(QPixmap("images/275665-200.png"), QIcon.Normal, QIcon.Off)
        self.back.setIcon(icon5)
        self.back.setIconSize(QSize(100, 100))
        self.back.setFlat(True)
        self.back.setObjectName("back")
        self.verticalLayout_5.addWidget(self.back)
        self.verticalLayout_2.addWidget(self.frame_6, 0,Qt.AlignTop)
        self.verticalLayout_3.addWidget(self.left)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.pages = QStackedWidget(self.content)
        self.pages.setObjectName("pages")
        self.home = QWidget()
        self.home.setObjectName("home")
        self.verticalLayout_13 = QVBoxLayout(self.home)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget = QWidget(self.home)
        self.widget.setObjectName("widget")
        self.verticalLayout_9 = QVBoxLayout(self.widget)
        self.verticalLayout_9.setContentsMargins(10, 50, 10, 50)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_title = QLabel(self.widget)
        font = QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(80)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(225, 37, 52);\n"
"font: 75 80pt \"MS Shell Dlg 2\";")
        self.label_title.setAlignment(Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_9.addWidget(self.label_title)
        self.label_description = QLabel(self.widget)
        font = QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_description.setFont(font)
        self.label_description.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 35pt \"MS Shell Dlg 2\";")
        self.label_description.setAlignment(Qt.AlignCenter)
        self.label_description.setObjectName("label_description")
        self.verticalLayout_9.addWidget(self.label_description)
        self.verticalLayout_13.addWidget(self.widget, 0, Qt.AlignHCenter|Qt.AlignVCenter)
        self.pages.addWidget(self.home)
        self.addcamera = QWidget()
        self.addcamera.setObjectName("addcamera")
        self.verticalLayout_12 = QVBoxLayout(self.addcamera)
        self.verticalLayout_12.setContentsMargins(-1,10, -1, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_14 = QLabel(self.addcamera)
        font = QFont()
        font.setFamily("Arial Black")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(225, 37, 52);\n"
"font: 87 30pt \"Arial Black\";")
        self.label_14.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_12.addWidget(self.label_14)
        self.verticalWidget_3 = QWidget(self.addcamera)
        self.verticalWidget_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 87 11pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.verticalWidget_3.setObjectName("verticalWidget_3")
        self.verticalLayout_11 = QVBoxLayout(self.verticalWidget_3)
        self.verticalLayout_11.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.verticalLayout_11.setContentsMargins(50, 40, 50, 40)
        self.verticalLayout_11.setSpacing(50)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_13 = QLabel(self.verticalWidget_3)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_11.addWidget(self.label_13)

        self.cameradep = QComboBox(self.verticalWidget_3)
        self.cameradep.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.cameradep.setObjectName("cameradep")
        self.verticalLayout_11.addWidget(self.cameradep)

        self.label_17 = QLabel(self.verticalWidget_3)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_11.addWidget(self.label_17)
        self.roomnumber = QComboBox(self.verticalWidget_3)
        self.roomnumber.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                      "color: rgb(0, 0, 0);")
        self.roomnumber.setObjectName("roomnumber")
        self.verticalLayout_11.addWidget(self.roomnumber)
        self.incorrectc = QLabel(self.verticalWidget_3)
        self.incorrectc.setText("")
        self.incorrectc.setObjectName("incorrect")
        self.incorrectc.setStyleSheet("color: rgb(225, 37, 52);\n"
                                     "font: 87 10pt \"Arial Black\";")
        self.verticalLayout_11.addWidget(self.incorrectc)
        self.camerasubmit = QPushButton(self.verticalWidget_3)
        self.camerasubmit.setObjectName("camerasubmit")
        self.verticalLayout_11.addWidget(self.camerasubmit)
        self.verticalLayout_12.addWidget(self.verticalWidget_3, 0, Qt.AlignHCenter|Qt.AlignVCenter)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(1, 4)
        self.pages.addWidget(self.addcamera)
        self.deletehead = QWidget()
        self.deletehead.setObjectName("deletehead")
        self.verticalLayout_6 =QVBoxLayout(self.deletehead)
        self.verticalLayout_6.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_21 = QLabel(self.deletehead)
        font =QFont()
        font.setFamily("Arial Black")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(225, 37, 52);\n"
                                    "font: 87 30pt \"Arial Black\";")
        self.label_21.setAlignment(Qt.AlignHCenter | Qt.AlignTop)
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_6.addWidget(self.label_21)
        self.verticalWidget_5 = QWidget(self.deletehead)
        self.verticalWidget_5.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                            "font: 87 11pt \"Arial Black\";\n"
                                            "color: rgb(255, 255, 255);")
        self.verticalWidget_5.setObjectName("verticalWidget_5")
        self.verticalLayout_15 = QVBoxLayout(self.verticalWidget_5)
        self.verticalLayout_15.setContentsMargins(50, 50, 50, 50)
        self.verticalLayout_15.setSpacing(50)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_4 = QLabel(self.verticalWidget_5)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_15.addWidget(self.label_4)
        self.deleteemail = QLineEdit(self.verticalWidget_5)
        self.deleteemail.setObjectName("deleteemail")
        self.verticalLayout_15.addWidget(self.deleteemail)
        self.incorrectd = QLabel(self.verticalWidget_5)
        self.incorrectd.setText("")
        self.incorrectd.setObjectName("incorrect")
        self.incorrectd.setStyleSheet("color: rgb(225, 37, 52);\n"
                                      "font: 87 10pt \"Arial Black\";")
        self.verticalLayout_15.addWidget(self.incorrectd)
        self.deletesubmit = QPushButton(self.verticalWidget_5)
        self.deletesubmit.setObjectName("deletesubmit")
        self.verticalLayout_15.addWidget(self.deletesubmit)
        self.verticalLayout_15.setStretch(0, 1)
        self.verticalLayout_15.setStretch(1, 5)
        self.verticalLayout_6.addWidget(self.verticalWidget_5, 0, Qt.AlignHCenter | Qt.AlignVCenter)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 6)
        self.pages.addWidget(self.deletehead)

        self.addhead = QWidget()
        self.addhead.setObjectName("addhead")
        self.verticalLayout_8 = QVBoxLayout(self.addhead)
        self.verticalLayout_8.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_12 = QLabel(self.addhead)
        font = QFont()
        font.setFamily("Arial Black")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(225, 37, 52);\n"
"font: 87 30pt \"Arial Black\";")
        self.label_12.setAlignment(Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_8.addWidget(self.label_12)
        self.verticalWidget_2 = QWidget(self.addhead)
        self.verticalWidget_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 87 11pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_7 = QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_7.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.verticalLayout_7.setContentsMargins(50, 40, 50, 40)
        self.verticalLayout_7.setSpacing(20)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QLabel(self.verticalWidget_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.headname = QLineEdit(self.verticalWidget_2)
        self.headname.setObjectName("headname")
        self.verticalLayout_7.addWidget(self.headname)
        self.label_8 = QLabel(self.verticalWidget_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.heademail = QLineEdit(self.verticalWidget_2)
        self.heademail.setObjectName("heademail")
        self.verticalLayout_7.addWidget(self.heademail)
        self.label_9 = QLabel(self.verticalWidget_2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.headpassword = QLineEdit(self.verticalWidget_2)
        self.headpassword.setInputMask("")
        self.headpassword.setEchoMode(QLineEdit.Password)
        self.headpassword.setObjectName("headpassword")
        self.verticalLayout_7.addWidget(self.headpassword)
        self.label_10 = QLabel(self.verticalWidget_2)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.headconfirmpass = QLineEdit(self.verticalWidget_2)
        self.headconfirmpass.setEchoMode(QLineEdit.Password)
        self.headconfirmpass.setObjectName("headconfirmpass")
        self.verticalLayout_7.addWidget(self.headconfirmpass)
        self.label_11 = QLabel(self.verticalWidget_2)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)
        self.headdep = QComboBox(self.verticalWidget_2)
        self.headdep.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.headdep.setObjectName("headdep")
        self.verticalLayout_7.addWidget(self.headdep)
        self.incorrecth = QLabel(self.verticalWidget_2)
        self.incorrecth.setText("")
        self.incorrecth.setObjectName("incorrect")
        self.incorrecth.setStyleSheet("color: rgb(225, 37, 52);\n"
                                     "font: 87 10pt \"Arial Black\";")
        self.verticalLayout_7.addWidget(self.incorrecth)

        self.headconfirm = QPushButton(self.verticalWidget_2)
        self.headconfirm.setObjectName("headconfirm")
        self.verticalLayout_7.addWidget(self.headconfirm)
        self.verticalLayout_8.addWidget(self.verticalWidget_2, 0, Qt.AlignHCenter|Qt.AlignVCenter)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 4)
        self.pages.addWidget(self.addhead)
        self.changepasswordPage = QWidget()
        self.changepasswordPage.setObjectName("changepasswordPage")
        self.verticalLayout_14 = QVBoxLayout(self.changepasswordPage)
        self.verticalLayout_14.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_15 = QLabel(self.changepasswordPage)
        font = QFont()
        font.setFamily("Arial Black")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(225, 37, 52);\n"
"font: 87 30pt \"Arial Black\";")
        self.label_15.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_14.addWidget(self.label_15)
        self.verticalWidget_4 = QWidget(self.changepasswordPage)
        self.verticalWidget_4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 87 11pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.verticalWidget_4.setObjectName("verticalWidget_4")
        self.verticalLayout_10 = QVBoxLayout(self.verticalWidget_4)
        self.verticalLayout_10.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.verticalLayout_10.setContentsMargins(50, 40, 50, 40)
        self.verticalLayout_10.setSpacing(20)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_16 = QLabel(self.verticalWidget_4)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_10.addWidget(self.label_16)
        self.previouspass = QLineEdit(self.verticalWidget_4)
        self.previouspass.setEchoMode(QLineEdit.Password)
        self.previouspass.setObjectName("previouspass")
        self.verticalLayout_10.addWidget(self.previouspass)
        self.label_19 = QLabel(self.verticalWidget_4)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_10.addWidget(self.label_19)
        self.newpass = QLineEdit(self.verticalWidget_4)
        self.newpass.setInputMask("")
        self.newpass.setEchoMode(QLineEdit.Password)
        self.newpass.setObjectName("newpass")
        self.verticalLayout_10.addWidget(self.newpass)
        self.label_20 = QLabel(self.verticalWidget_4)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_10.addWidget(self.label_20)
        self.confirmnewpass = QLineEdit(self.verticalWidget_4)
        self.confirmnewpass.setEchoMode(QLineEdit.Password)
        self.confirmnewpass.setObjectName("confirmnewpass")
        self.verticalLayout_10.addWidget(self.confirmnewpass)
        self.incorrectp = QLabel(self.verticalWidget_4)
        self.incorrectp.setText("")
        self.incorrectp.setObjectName("incorrect")
        self.incorrectp.setStyleSheet("color: rgb(225, 37, 52);\n"
                                     "font: 87 10pt \"Arial Black\";")
        self.verticalLayout_10.addWidget(self.incorrectp)
        self.confirmchange = QPushButton(self.verticalWidget_4)
        self.confirmchange.setObjectName("confirmchange")
        self.verticalLayout_10.addWidget(self.confirmchange)
        self.verticalLayout_14.addWidget(self.verticalWidget_4, 0, Qt.AlignHCenter|Qt.AlignVCenter)
        self.verticalLayout_14.setStretch(0, 1)
        self.verticalLayout_14.setStretch(1, 4)
        self.pages.addWidget(self.changepasswordPage)
        self.horizontalLayout_2.addWidget(self.pages)
        self.verticalLayout.addWidget(self.content)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 10)
        headSettingsMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(headSettingsMainWindow)
        self.pages.setCurrentIndex(0)
        QMetaObject.connectSlotsByName(headSettingsMainWindow)

    def retranslateUi(self, SettingsMainWindow):
        SettingsMainWindow.setWindowTitle(QCoreApplication.translate("SettingsMainWindow", "Settings"))
        self.label_6.setText(QCoreApplication.translate("SettingsMainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">change password </span></p></body></html>",None))
        self.label_5.setText(QCoreApplication.translate("SettingsMainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">logout</span></p></body></html>",None))
        self.label_title.setText(QCoreApplication.translate("SettingsMainWindow", "<html><head/><body><p>AURORA</p></body></html>",None))
        self.label_description.setText(QCoreApplication.translate("SettingsMainWindow", "<html><head/><body><p>an eye on every detail</p></body></html>",None))
        self.label_14.setText(QCoreApplication.translate("SettingsMainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#f00000;\">ADD CAMERA</span></p></body></html>",None))
        self.label_13.setText(QCoreApplication.translate("SettingsMainWindow", "choose department:",None))
        self.label_17.setText(QCoreApplication.translate("SettingsMainWindow", "choose room:",None))
        self.cameradep.setCurrentText(QCoreApplication.translate("SettingsMainWindow", "none",None))
        self.roomnumber.setCurrentText(QCoreApplication.translate("SettingsMainWindow", "none", None))
        self.camerasubmit.setText(QCoreApplication.translate("SettingsMainWindow", "submit",None))
        self.label_12.setText(QCoreApplication.translate("SettingsMainWindow", "<html><head/><body><p><span style=\" color:#f00000;\">ADD HEAD OF DEPARTMENT     </span></p></body></html>",None))
        self.label_7.setText(QCoreApplication.translate("SettingsMainWindow", "enter Name:",None))
        self.label_8.setText(QCoreApplication.translate("SettingsMainWindow", "enter email address:",None))
        self.label_9.setText(QCoreApplication.translate("SettingsMainWindow", "enter password:",None))
        self.label_10.setText(QCoreApplication.translate("SettingsMainWindow", "confirm password:",None))
        self.label_11.setText(QCoreApplication.translate("SettingsMainWindow", "choose department:",None))
        self.headdep.setCurrentText(QCoreApplication.translate("SettingsMainWindow", "none",None))
        self.headconfirm.setText(QCoreApplication.translate("SettingsMainWindow", "submit",None))
        self.label_15.setText(QCoreApplication.translate("SettingsMainWindow", "<html><head/><body><p align=\"center\">CHANGE PASSWORD</p></body></html>",None))
        self.label_16.setText(QCoreApplication.translate("SettingsMainWindow", "enter previous password:",None))
        self.label_19.setText(QCoreApplication.translate("SettingsMainWindow", "enter new password:",None))
        self.label_20.setText(QCoreApplication.translate("SettingsMainWindow", "confirm new  password:",None))
        self.label_4.setText(QCoreApplication.translate("SettingsMainWindow", "Enter Email:",None))
        self.deletesubmit.setText(QCoreApplication.translate("SettingsMainWindow", "delete",None))
        self.label_21.setText(QCoreApplication.translate("SettingsMainWindow",
                                         "<html><head/><body><p align=\"center\">REMOVE HEAD OF DEPARTMENT</p></body></html>",None))
        self.confirmchange.setText(QCoreApplication.translate("SettingsMainWindow", "submit",None))

