# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screenshots.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pickle
import os
import cv2
import cameras

class Ui_ScreenShots(object):

    def __init__(self):
                self.sc = pickle.load(open("sc.dat", "rb"))

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.showMaximized()
        MainWindow.setStyleSheet("QMainWindow{\n"
"\n"
"\n"
"background-image: url(images/new.png);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listofimages = QtWidgets.QListWidget(self.centralwidget)
        self.listofimages.setObjectName("listofimages")
        self.verticalLayout.addWidget(self.listofimages)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/275665-200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(100, 80))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda:self.back_button(MainWindow))
        self.verticalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget_4.setObjectName("verticalWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalWidget_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2.addWidget(self.verticalWidget_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.photoviewer = QtWidgets.QLabel(self.centralwidget)
        self.photoviewer.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.photoviewer.setText("")
        self.photoviewer.setMaximumSize(630,490)
        self.photoviewer.setObjectName("photoviewer")
        self.listofimages.itemDoubleClicked.connect(lambda:self.display_image(self.listofimages.currentItem().text()))
        self.verticalLayout_2.addWidget(self.photoviewer)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.time = QtWidgets.QLabel(self.centralwidget)
        self.time.setObjectName("time")
        self.horizontalLayout_2.addWidget(self.time)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 8)
        self.verticalLayout_2.setStretch(2, 3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 5)
        self.horizontalLayout.setStretch(3, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.load_images(self.sc)
        self.screen=MainWindow

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">           ScreenShots :</p></body></html>"))
        self.time.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Time taken:</span></p></body></html>"))

    def load_images(self,id):
        Directory = os.path.dirname(os.path.abspath(__file__))  # return directory of current file
        path = os.path.join(Directory,"%d"%(id))
        list=os.listdir(path)
        for cls in list:
            img=cv2.imread(os.path.join(path,cls))
            pixmap=QtGui.QPixmap(os.path.join(path,cls))
            icon=QtGui.QIcon(pixmap)
            item=QtWidgets.QListWidgetItem()
            item.setIcon(icon)
            m=str(os.path.splitext(cls)[0])
            if not m=="Thumbs":
                l=m.split("-Time-")
                date=l[0]
                l1=l[1].split("-persons-")
                persons=l1[1]
                l2=l1[0].split("-")
                s="Date:"+date+"\n Time:"+l2[0]+":"+l2[1]+":"+l2[2]+"\n persons:"+persons
                item.setText(m)
                self.listofimages.addItem(item)

    def display_image(self,string):
        # find directory of images
        Directory = os.path.dirname(os.path.abspath(__file__))  # return directory of current file
        path = os.path.join(Directory,"%d"%self.sc)
        pixmap=QtGui.QPixmap("%s/%s.png"%(path,string))
        l = string.split("-Time-")
        date = l[0]
        l1 = l[1].split("-persons-")
        persons = l1[1]
        l2 = l1[0].split("-")
        s = "Date:" + date + "\n Time:" + l2[0] + ":" + l2[1] + ":" + l2[2] + "\n persons:" + persons
        self.photoviewer.setPixmap(pixmap)
        self.time.setText("<strong>Date:"+s+"</strong>")


    def back_button(self,MainWindow):
        pickle.dump("no",open("sc.dat","wb"))
        self.window = QtWidgets.QMainWindow()
        self.ui=cameras.Ui_CameraMainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.screen.close()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_ScreenShots()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
